import type {Component} from "vue";
import {
  Archive,
  ArchiveRestore,
  Box,
  Braces,
  BrushCleaning,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardPaste,
  Columns3,
  Copy,
  Download,
  Eye,
  File,
  FileArchive,
  FileBox,
  FileChartColumn,
  FileCode,
  FileCog,
  FileImage,
  FileMusic,
  FilePlus,
  FileQuestionMark,
  FileSpreadsheet,
  FileText,
  FileType,
  Folder,
  FolderOpen,
  FolderPlus,
  Grid2X2,
  House,
  Image,
  LayoutGrid,
  List,
  Lock,
  LogOut,
  Maximize2,
  MoreHorizontal,
  Minimize2,
  PanelRight,
  PanelRightClose,
  Pencil,
  Plus,
  RefreshCw,
  Rows3,
  Save,
  Scissors,
  Search,
  Settings,
  Share2,
  SquarePen,
  Terminal,
  Trash2,
  Upload,
  User,
  Video,
  Wrench,
  X
} from "lucide-vue-next";
import type {AppIconPack} from "./types.ts";

const lucideIcons: Record<string, Component> = {
  "action.upload": Upload,
  "action.new-file": FilePlus,
  "action.new-folder": FolderPlus,
  "action.cut": Scissors,
  "action.copy": Copy,
  "action.paste": ClipboardPaste,
  "action.download": Download,
  "action.preview": Eye,
  "action.archive": Archive,
  "action.extract": ArchiveRestore,
  "action.restore": ArchiveRestore,
  "action.rename": Pencil,
  "action.delete": Trash2,
  "action.trash": Trash2,
  "action.edit": SquarePen,
  "action.save": Save,
  "action.close": X,
  "action.add": Plus,
  "action.refresh": RefreshCw,
  "action.clean": BrushCleaning,
  "action.settings": Settings,
  "action.more": MoreHorizontal,
  "action.logout": LogOut,
  "action.search": Search,
  "action.share": Share2,
  "action.fullscreen": Maximize2,
  "action.exit-fullscreen": Minimize2,
  "action.previous": ChevronLeft,
  "action.next": ChevronRight,
  "action.up": ChevronUp,
  "action.down": ChevronDown,
  "action.tools": Wrench,

  "view.details": List,
  "view.list": Rows3,
  "view.icons": LayoutGrid,
  "view.tiles": Columns3,
  "view.grid": Grid2X2,
  "view.preview-pane": PanelRight,
  "view.preview-pane-close": PanelRightClose,
  "view.image": Image,

  "file.home": House,
  "file.folder": Folder,
  "file.folder-open": FolderOpen,
  "file.file": File,
  "file.image": FileImage,
  "file.text": FileText,
  "file.code": FileCode,
  "file.config": FileCog,
  "file.archive": FileArchive,
  "file.audio": FileMusic,
  "file.video": Video,
  "file.pdf": FileText,
  "file.spreadsheet": FileSpreadsheet,
  "file.document": FileText,
  "file.presentation": FileChartColumn,
  "file.executable": Terminal,
  "file.shortcut": Share2,
  "file.database": FileBox,
  "file.font": FileType,
  "file.package": Box,
  "file.markup": Braces,
  "file.unknown": FileQuestionMark,
  "file.generic": File,

  "icon-upload": Upload,
  "icon-file-add-fill": FilePlus,
  "icon-folder-add-fill": FolderPlus,
  "icon-scissors": Scissors,
  "icon-contentcut": Scissors,
  "icon-copy": Copy,
  "icon-copy1": Copy,
  "icon-paste": ClipboardPaste,
  "icon-download": Download,
  "icon-download1": Download,
  "icon-download2": Download,
  "icon-download2f": Download,
  "icon-edit-filling": SquarePen,
  "icon-rename": Pencil,
  "icon-bx-rename": Pencil,
  "icon-renamebox": SquarePen,
  "icon-delete": Trash2,
  "icon-delete1": Trash2,
  "icon-delete-fill": Trash2,
  "icon-setting": Settings,
  "icon-setting-filling": Settings,
  "icon-wrench": Wrench,
  "icon-password": Lock,
  "icon-user-fill": User,
  "icon-save-fill": Save,
  "icon-close": X,
  "icon-add": Plus,
  "icon-refresh": RefreshCw,
  "icon-back_android": ChevronLeft,
  "icon-unfold": ChevronDown,
  "icon-fenxiang": Search,
  "icon-viewgrid": LayoutGrid,
  "icon-view-list": List,
  "icon-listview": Rows3,
  "icon-homefill": House,
  "icon-home-fill": House,
  "icon-file": File,
  "icon-file-fill": File,
  "icon-file-common-filling": FileText,
  "icon-file-image-fill": FileImage,
  "icon-file-zip": FileArchive,
  "icon-file-zip-fill": FileArchive,
  "icon-folder": Folder,
  "icon-folder-fill": Folder,
  "icon-folder-open-fill": FolderOpen
};

export const lucideIconPack: AppIconPack = {
  resolve(icon) {
    const component = lucideIcons[icon];
    return component ? {kind: "component", component, className: "app-icon-lucide"} : undefined;
  }
};
